#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("JudoDotNetXamarinAndroidSDK.Resource", IsApplication=true)]

namespace JudoDotNetXamarinAndroidSDK
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_in_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fade_out = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int flipping_in = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int flipping_in_vert = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int flipping_out = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int flipping_out_vert = 2130968582;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int avs_countries = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int avs_countries_postcode_label_text = 2131165185;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f08000c
			public const int accent = 2131230732;
			
			// aapt resource value: 0x7f080002
			public const int action_bar_bg = 2131230722;
			
			// aapt resource value: 0x7f080017
			public const int button_main_bg = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int button_main_bg_ripple = 2131230744;
			
			// aapt resource value: 0x7f080008
			public const int button_text = 2131230728;
			
			// aapt resource value: 0x7f080015
			public const int cancel_bg = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int cancel_bg_ripple = 2131230742;
			
			// aapt resource value: 0x7f080009
			public const int cancel_text = 2131230729;
			
			// aapt resource value: 0x7f080014
			public const int card_off = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int card_on = 2131230739;
			
			// aapt resource value: 0x7f080019
			public const int debug0 = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int debug1 = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int debug2 = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int debug3 = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int debug4 = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int debug5 = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int debug6 = 2131230751;
			
			// aapt resource value: 0x7f080004
			public const int default_text = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int error_bg = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int error_text = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int hint_text = 2131230725;
			
			// aapt resource value: 0x7f08000f
			public const int list_cell_bg = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int list_divider = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int list_selector_pressed = 2131230737;
			
			// aapt resource value: 0x7f080000
			public const int normal_text = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int page_bg = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int page_divider = 2131230723;
			
			// aapt resource value: 0x7f08000a
			public const int primary = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int primary_dark = 2131230731;
			
			// aapt resource value: 0x7f080012
			public const int prog_dialog_bg = 2131230738;
			
			// aapt resource value: 0x7f08000d
			public const int splash_bg = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int white_transparent = 2131230734;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0010
			public const int action_bar_icon_right_padding = 2131361808;
			
			// aapt resource value: 0x7f0a0007
			public const int activity_horizontal_margin = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int activity_vertical_margin = 2131361800;
			
			// aapt resource value: 0x7f0a0000
			public const int avs_container_height = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int avs_msg_height = 2131361793;
			
			// aapt resource value: 0x7f0a0006
			public const int backgroundhinttextview_error_vertical_padding = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int backgroundhinttextview_horizontal_padding = 2131361797;
			
			// aapt resource value: 0x7f0a000c
			public const int button_text_size = 2131361804;
			
			// aapt resource value: 0x7f0a000f
			public const int cancel_button_height = 2131361807;
			
			// aapt resource value: 0x7f0a0003
			public const int cardnumber_container_height = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int default_backgroundhinttextview_container_height = 2131361796;
			
			// aapt resource value: 0x7f0a000a
			public const int default_text_size = 2131361802;
			
			// aapt resource value: 0x7f0a000e
			public const int error_text_size = 2131361806;
			
			// aapt resource value: 0x7f0a0009
			public const int general_padding = 2131361801;
			
			// aapt resource value: 0x7f0a000d
			public const int small_text_size = 2131361805;
			
			// aapt resource value: 0x7f0a0002
			public const int startdate_container_height = 2131361794;
			
			// aapt resource value: 0x7f0a000b
			public const int title_text_size = 2131361803;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_solid_judo_payments = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int app_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_default_disabled_focused_holo_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_default_disabled_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_default_focused_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_default_normal_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_default_pressed_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_settings = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_settings_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_yellow_disabled_focused_holo_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_yellow_disabled_holo_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_yellow_focused_holo_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_yellow_normal_holo_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_yellow_pressed_holo_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int button_settings = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int cab_background_top_judo_payments = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int edit_text_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int field = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int gold_button_bg = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int grey_button_bg = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_3ds_logos = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_actionbar_bg_shadow_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_app_icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_card_amex = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_card_cv2 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_card_cv2_amex = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_card_large_amex = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_card_large_cv2 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_card_large_cv2_amex = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_card_large_maestro = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_card_large_mastercard = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_card_large_unknown = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_card_large_visa = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_card_logo_strip = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_card_maestro = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_card_mastercard = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_card_unknown = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_card_visa = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_home = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_info = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_lock = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int list_focused_judo_payments = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int list_pressed_judo_payments = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int loader_1 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int loader_10 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int loader_11 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int loader_12 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int loader_2 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int loader_3 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int loader_4 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int loader_5 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int loader_6 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int loader_7 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int loader_8 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int loader_9 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int main_button_background = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int progress_spinner = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int secondary_button_background = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int selectable_background_judo_payments = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int spinner_background_judo_payments = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int spinner_default = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int spinner_disabled = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int spinner_focused = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int spinner_list_activated_holo = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int spinner_list_focused_holo = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int spinner_list_longpressed_holo = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int spinner_list_pressed_holo_light = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int spinner_list_selector_disabled_holo_light = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int spinner_pressed = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int textfield_activated_holo_light = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int textfield_default_holo_light = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int textfield_disabled_focused_holo_light = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int textfield_disabled_holo_light = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int textfield_focused_holo_light = 2130837577;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0010
			public const int addressLine1 = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int addressLine2 = 2131492881;
			
			// aapt resource value: 0x7f0c0012
			public const int addressLine3 = 2131492882;
			
			// aapt resource value: 0x7f0c0014
			public const int addressPostCode = 2131492884;
			
			// aapt resource value: 0x7f0c0013
			public const int addressTown = 2131492883;
			
			// aapt resource value: 0x7f0c000c
			public const int avsEntryView = 2131492876;
			
			// aapt resource value: 0x7f0c0006
			public const int avsMsgText = 2131492870;
			
			// aapt resource value: 0x7f0c000e
			public const int cancelButton = 2131492878;
			
			// aapt resource value: 0x7f0c0009
			public const int cardEntryView = 2131492873;
			
			// aapt resource value: 0x7f0c0000
			public const int countrySpinner = 2131492864;
			
			// aapt resource value: 0x7f0c001b
			public const int cv2EntryView = 2131492891;
			
			// aapt resource value: 0x7f0c0007
			public const int hintTextView = 2131492871;
			
			// aapt resource value: 0x7f0c000a
			public const int infoButtonID = 2131492874;
			
			// aapt resource value: 0x7f0c0018
			public const int issueNumberContainer = 2131492888;
			
			// aapt resource value: 0x7f0c001a
			public const int issueNumberEditText = 2131492890;
			
			// aapt resource value: 0x7f0c0019
			public const int issueNumberTitleText = 2131492889;
			
			// aapt resource value: 0x7f0c000f
			public const int loadingLayout = 2131492879;
			
			// aapt resource value: 0x7f0c000d
			public const int payButton = 2131492877;
			
			// aapt resource value: 0x7f0c0002
			public const int postCodeContainer = 2131492866;
			
			// aapt resource value: 0x7f0c0004
			public const int postCodeEditText = 2131492868;
			
			// aapt resource value: 0x7f0c0005
			public const int postCodeHelpButton = 2131492869;
			
			// aapt resource value: 0x7f0c0003
			public const int postCodeTitleText = 2131492867;
			
			// aapt resource value: 0x7f0c0001
			public const int postCode_Msg = 2131492865;
			
			// aapt resource value: 0x7f0c0008
			public const int secureview = 2131492872;
			
			// aapt resource value: 0x7f0c0015
			public const int startDateContainer = 2131492885;
			
			// aapt resource value: 0x7f0c0017
			public const int startDateEditText = 2131492887;
			
			// aapt resource value: 0x7f0c000b
			public const int startDateEntryView = 2131492875;
			
			// aapt resource value: 0x7f0c0016
			public const int startDateTitleText = 2131492886;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int progressFrameDuration = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int avs = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int country_spinner_dropdown_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int payment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int register_card = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int secure3d = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int security = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int startdate_and_issuenumber = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int token_payment = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int courier = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060009
			public const int address_line1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int address_line2 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int address_line3 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int address_postcode = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int address_town = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f06002b
			public const int billing_country = 2131099691;
			
			// aapt resource value: 0x7f060010
			public const int cancel = 2131099664;
			
			// aapt resource value: 0x7f060032
			public const int card_no_obscured = 2131099698;
			
			// aapt resource value: 0x7f060008
			public const int enter_card_cv2 = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int enter_card_expiry = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int enter_card_no = 2131099654;
			
			// aapt resource value: 0x7f060014
			public const int help_amount_header = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int help_amount_text = 2131099669;
			
			// aapt resource value: 0x7f06001c
			public const int help_card_header = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int help_card_text = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public const int help_cv2_text = 2131099679;
			
			// aapt resource value: 0x7f06001a
			public const int help_email_header = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int help_email_text = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int help_info = 2131099678;
			
			// aapt resource value: 0x7f060016
			public const int help_judo_header = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int help_judo_text = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int help_mob_header = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int help_mob_text = 2131099673;
			
			// aapt resource value: 0x7f060021
			public const int help_postcode_text = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int help_postcode_title = 2131099680;
			
			// aapt resource value: 0x7f060035
			public const int hint_issue_number = 2131099701;
			
			// aapt resource value: 0x7f06002d
			public const int hint_postcode = 2131099693;
			
			// aapt resource value: 0x7f06002f
			public const int hint_start_date = 2131099695;
			
			// aapt resource value: 0x7f060034
			public const int issue_number = 2131099700;
			
			// aapt resource value: 0x7f060038
			public const int msg_avs_info_others = 2131099704;
			
			// aapt resource value: 0x7f060031
			public const int msg_card_no_invalid = 2131099697;
			
			// aapt resource value: 0x7f060033
			public const int msg_check_exp_date = 2131099699;
			
			// aapt resource value: 0x7f060037
			public const int msg_check_issue_number = 2131099703;
			
			// aapt resource value: 0x7f060030
			public const int msg_check_number = 2131099696;
			
			// aapt resource value: 0x7f060036
			public const int msg_check_start_date = 2131099702;
			
			// aapt resource value: 0x7f06000f
			public const int ok = 2131099663;
			
			// aapt resource value: 0x7f060026
			public const int payment = 2131099686;
			
			// aapt resource value: 0x7f060023
			public const int payment_button = 2131099683;
			
			// aapt resource value: 0x7f060011
			public const int payment_hint_amt = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int payment_hint_cv2 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int payment_hint_enter_amt_with_currency = 2131099667;
			
			// aapt resource value: 0x7f060022
			public const int payment_hint_judo = 2131099682;
			
			// aapt resource value: 0x7f06002c
			public const int postcode = 2131099692;
			
			// aapt resource value: 0x7f060028
			public const int preauth = 2131099688;
			
			// aapt resource value: 0x7f060025
			public const int register_card = 2131099685;
			
			// aapt resource value: 0x7f06002a
			public const int secure3dtext = 2131099690;
			
			// aapt resource value: 0x7f060024
			public const int security_message = 2131099684;
			
			// aapt resource value: 0x7f06002e
			public const int start_date = 2131099694;
			
			// aapt resource value: 0x7f06000e
			public const int submit = 2131099662;
			
			// aapt resource value: 0x7f060001
			public const int title_payment = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int title_payment_token = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int title_pre_auth = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int title_pre_auth_token = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int title_register_card = 2131099653;
			
			// aapt resource value: 0x7f060027
			public const int token_payment = 2131099687;
			
			// aapt resource value: 0x7f060029
			public const int token_preauth = 2131099689;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b0021
			public const int ActionBar_Solid_Judo_payments = 2131427361;
			
			// aapt resource value: 0x7f0b0022
			public const int ActionBar_TitleTextStyle_Judo_payments = 2131427362;
			
			// aapt resource value: 0x7f0b001f
			public const int Theme_Judo_payments = 2131427359;
			
			// aapt resource value: 0x7f0b001e
			public const int Theme_Judo_payments_base = 2131427358;
			
			// aapt resource value: 0x7f0b000b
			public const int judo_payments_AddressEditText = 2131427339;
			
			// aapt resource value: 0x7f0b0020
			public const int judo_payments_BaseButton = 2131427360;
			
			// aapt resource value: 0x7f0b000e
			public const int judo_payments_Button = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int judo_payments_Button_Main = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int judo_payments_Button_Secondary = 2131427344;
			
			// aapt resource value: 0x7f0b0017
			public const int judo_payments_CardText = 2131427351;
			
			// aapt resource value: 0x7f0b0016
			public const int judo_payments_ContainerFrame = 2131427350;
			
			// aapt resource value: 0x7f0b000a
			public const int judo_payments_EditText = 2131427338;
			
			// aapt resource value: 0x7f0b000d
			public const int judo_payments_EditText_Single = 2131427341;
			
			// aapt resource value: 0x7f0b0019
			public const int judo_payments_ErrorText = 2131427353;
			
			// aapt resource value: 0x7f0b0018
			public const int judo_payments_HintText = 2131427352;
			
			// aapt resource value: 0x7f0b0012
			public const int judo_payments_InfoButton = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public const int judo_payments_InfoButton_Home = 2131427347;
			
			// aapt resource value: 0x7f0b0014
			public const int judo_payments_InputContainer = 2131427348;
			
			// aapt resource value: 0x7f0b001a
			public const int judo_payments_InputFieldContainer = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public const int judo_payments_ProgressBar = 2131427355;
			
			// aapt resource value: 0x7f0b001c
			public const int judo_payments_ProgressDialog = 2131427356;
			
			// aapt resource value: 0x7f0b001d
			public const int judo_payments_ProgressDialogAnim = 2131427357;
			
			// aapt resource value: 0x7f0b0015
			public const int judo_payments_SettingsButton = 2131427349;
			
			// aapt resource value: 0x7f0b000c
			public const int judo_payments_Spinner = 2131427340;
			
			// aapt resource value: 0x7f0b0011
			public const int judo_payments_Title = 2131427345;
			
			// aapt resource value: 0x7f0b0008
			public const int judo_payments_cardstrip = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int judo_payments_divider = 2131427337;
			
			// aapt resource value: 0x7f0b0002
			public const int judo_payments_label = 2131427330;
			
			// aapt resource value: 0x7f0b0004
			public const int judo_payments_label_Left = 2131427332;
			
			// aapt resource value: 0x7f0b0003
			public const int judo_payments_label_ReceiptList = 2131427331;
			
			// aapt resource value: 0x7f0b0005
			public const int judo_payments_label_Right = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int judo_payments_label_RightIcon = 2131427334;
			
			// aapt resource value: 0x7f0b0001
			public const int judo_payments_message = 2131427329;
			
			// aapt resource value: 0x7f0b0000
			public const int judo_payments_page = 2131427328;
			
			// aapt resource value: 0x7f0b0007
			public const int judo_payments_spacer = 2131427335;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
