#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("StripeSampleAndroid.Resource", IsApplication=true)]

namespace StripeSampleAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Stripe.Resource.Drawable.amex = global::StripeSampleAndroid.Resource.Drawable.amex;
			global::Stripe.Resource.Drawable.credit = global::StripeSampleAndroid.Resource.Drawable.credit;
			global::Stripe.Resource.Drawable.cvc = global::StripeSampleAndroid.Resource.Drawable.cvc;
			global::Stripe.Resource.Drawable.diners = global::StripeSampleAndroid.Resource.Drawable.diners;
			global::Stripe.Resource.Drawable.discover = global::StripeSampleAndroid.Resource.Drawable.discover;
			global::Stripe.Resource.Drawable.jcb = global::StripeSampleAndroid.Resource.Drawable.jcb;
			global::Stripe.Resource.Drawable.maestro = global::StripeSampleAndroid.Resource.Drawable.maestro;
			global::Stripe.Resource.Drawable.mastercard = global::StripeSampleAndroid.Resource.Drawable.mastercard;
			global::Stripe.Resource.Drawable.visa = global::StripeSampleAndroid.Resource.Drawable.visa;
			global::Stripe.Resource.Id.stripeCvc = global::StripeSampleAndroid.Resource.Id.stripeCvc;
			global::Stripe.Resource.Id.stripeExpiration = global::StripeSampleAndroid.Resource.Id.stripeExpiration;
			global::Stripe.Resource.Id.stripeImage = global::StripeSampleAndroid.Resource.Id.stripeImage;
			global::Stripe.Resource.Id.stripeLastFour = global::StripeSampleAndroid.Resource.Id.stripeLastFour;
			global::Stripe.Resource.Id.stripeLayoutOne = global::StripeSampleAndroid.Resource.Id.stripeLayoutOne;
			global::Stripe.Resource.Id.stripeLayoutTwo = global::StripeSampleAndroid.Resource.Id.stripeLayoutTwo;
			global::Stripe.Resource.Id.stripeNumber = global::StripeSampleAndroid.Resource.Id.stripeNumber;
			global::Stripe.Resource.Layout.stripeviewlayout = global::StripeSampleAndroid.Resource.Layout.stripeviewlayout;
			global::Stripe.Resource.String.library_name = global::StripeSampleAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int amex = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int credit = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cvc = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int diners = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int discover = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int jcb = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int maestro = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mastercard = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int paypal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int visa = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int address1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int address2 = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int buttonToken = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int city = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int country = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int name = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int state = 2131034117;
			
			// aapt resource value: 0x7f05000f
			public const int stripeCvc = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int stripeExpiration = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int stripeImage = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int stripeLastFour = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int stripeLayoutOne = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int stripeLayoutTwo = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int stripeNumber = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int stripeView = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int zip = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int stripeviewlayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
